workflows:
  ios-workflow:
    name: MaintMENA iOS (Capacitor)
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.maintmena.app

      vars:
        # Put your real App Store Connect Apple ID here (after you create the app)
        APP_STORE_APPLE_ID: 0000000000

        # These match a standard Capacitor iOS structure
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install npm dependencies
        script: |
          npm ci

      - name: Build web (dist)
        script: |
          npm run build

      - name: Sync Capacitor (copy web assets + update native deps)
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Set up code signing settings
        script: |
          cd ios/App
          xcode-project use-profiles

      
      - name: Build IPA for distribution
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/App/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
